# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk

# Set the working directory in the container
WORKDIR /demo

# Copy the build output from Maven or Gradle to the working directory
COPY target/task-management-system-0.0.1-SNAPSHOT.jar /demo/TaskManagementSystem.jar

# Expose the port on which the app will run
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "/demo/TaskManagementSystem.jar"]
